# Generated by Django 4.1 on 2022-12-08 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('TWO-VEHICLE', 'TWO-VEHICLE'), ('THREE-VEHICLE', 'THREE-VEHICLE'), ('FOUR-VEHICLE', 'FOUR-VEHICLE')], default='TWO-VEHCICLE', max_length=30)),
                ('manufacture_company', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('deleted', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
