# Generated by Django 4.1 on 2023-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO-WHEELER', 'TWO-WHEELER'), ('THREE-WHEELER', 'THREE-WHEELER'), ('FOUR-WHEELER', 'FOUR-WHEELER')], default='TWO-VEHCICLE', max_length=30),
        ),
    ]
