# Generated by Django 4.1 on 2023-01-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='station',
            new_name='station_id',
        ),
    ]
