# Generated by Django 4.1 on 2023-01-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_rename_station_slot_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='station_id',
            new_name='station',
        ),
    ]
