# Generated by Django 4.1 on 2023-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='user_type',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='station',
            name='give_feedback',
        ),
        migrations.AlterField(
            model_name='station',
            name='station_address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
