# Generated by Django 4.1 on 2023-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_rename_user_type_station_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='station',
            name='update_by',
            field=models.IntegerField(default=1),
        ),
    ]
